services:
  db:
    image: postgres:16.2
    container_name: postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_dev_data:/var/lib/postgresql/data

  test_db:
    image: postgres:16.2
    container_name: postgres_test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_TEST}

volumes:
  pg_dev_data:
